#!/usr/bin/python

# Usage:
#
#   ssh git@git.baserock.org ls | ./find-missing-lorries


import glob
import os
import sys
import json


repo_list = []
for line in sys.stdin:
    words = line.split()
    repo_list.append(words[1])


lorries = []
for filename in glob.glob('open-source-lorries/*.lorry'):
    with open(filename) as f:
        obj = json.load(f)
    for repo_basename in obj:
        repo_name = 'delta/%s' % repo_basename
        lorries.append(repo_name)


for repo in repo_list:
    if repo.startswith('delta/') and repo not in lorries:
        print 'MISSING', repo
